<div class="modal fade" id="turnoModal" name="turnoModal" tabindex="-1" role="dialog" aria-labelledby="turnoModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="turnoModalLabel">Turnos</h5>               
            </div>
            <div class="modal-body">
                <table id="tabelaTurnos" name="tabelaTurnos" class="table table-bordered">
                    <thead>
                        <tr>                                        
                            <th>Rodada</th>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                            <th>Turno</th>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                            <th>Ação</th>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                            <th>Jogador Origem</th>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                            <th>Jogador Destino</th>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                            <th>Dano</th>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                            <th>Efeito</th>
                            <th>Duração Efeito</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>                           
            </div>
            <div class="modal-footer">
                <button id="btnCancelarModalT" name="btnCancelarModalT" type="button" class="btn btn-secondary"  data-dismiss="modal">Cancelar</button>                
            </div>
        </div>
    </div>
</div>
